groups:
- name: Critical alers
  rules:
  
  - alert: InstanceDown
    expr: up == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: Instance {{ $labels.instance }} downestart=on-failure
      description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute.'

  - alert: high_load
    expr: container_fs_limit_bytes > 0
    for: 2m
    labels:
      severity: page
    annotations:
      summary: "Instance {{ $labels.instance }} under high load"
      description: "{{ $labels.instance }} of job {{ $labels.job }} is under high load."
